/**
 * Deterministic observations over stored results.
 *
 * Nothing here is generated by a language model and nothing here is a
 * diagnosis. Every statement is a arithmetic comparison of two values that were
 * extracted from the patient's own documents, phrased as an observation
 * ("increased", "returned to range") rather than a clinical conclusion.
 *
 * Keeping this separate from the LLM path is deliberate: the numbers a patient
 * sees must be reproducible and explainable, so they are computed here and the
 * model is only ever allowed to rephrase them.
 */
import { ExtractedParameter } from './ai.service';

export type TrendDirection = 'INCREASED' | 'DECREASED' | 'STABLE' | 'SINGLE';

export interface TrendPoint {
  recordId: string;
  fileName: string;
  date: Date | string;
  value: number;
  status: string;
}

export interface TrendObservation {
  direction: TrendDirection;
  /** Signed change between the two most recent readings. */
  delta: number;
  deltaPercent: number | null;
  /** Plain, non-diagnostic sentence. Safe to render verbatim. */
  note: string;
  /** Was normal, now out of range. */
  newlyAbnormal: boolean;
  /** Was out of range, now normal. */
  returnedToRange: boolean;
}

/** Below this relative change two readings are reported as unchanged. */
const STABLE_THRESHOLD = 0.05;

export function describeTrend(
  points: TrendPoint[],
  testName: string,
  unit: string
): TrendObservation {
  if (points.length < 2) {
    return {
      direction: 'SINGLE',
      delta: 0,
      deltaPercent: null,
      note: `Only one reading of ${testName} is on file, so no change can be shown yet.`,
      newlyAbnormal: false,
      returnedToRange: false,
    };
  }

  const latest = points[points.length - 1]!;
  const previous = points[points.length - 2]!;
  const delta = latest.value - previous.value;
  const deltaPercent = previous.value !== 0 ? (delta / Math.abs(previous.value)) * 100 : null;

  const relative = previous.value !== 0 ? Math.abs(delta / previous.value) : Math.abs(delta);
  const direction: TrendDirection =
    relative < STABLE_THRESHOLD ? 'STABLE' : delta > 0 ? 'INCREASED' : 'DECREASED';

  const wasAbnormal = previous.status === 'HIGH' || previous.status === 'LOW';
  const isAbnormal = latest.status === 'HIGH' || latest.status === 'LOW';
  const newlyAbnormal = !wasAbnormal && isAbnormal;
  const returnedToRange = wasAbnormal && latest.status === 'NORMAL';

  const magnitude = `${Math.abs(delta).toFixed(Math.abs(delta) < 1 ? 2 : 1)}${unit ? ` ${unit}` : ''}`;
  const movement =
    direction === 'STABLE'
      ? `${testName} is essentially unchanged since the previous report`
      : `${testName} ${direction === 'INCREASED' ? 'increased' : 'decreased'} by ${magnitude} since the previous report`;

  let note = `${movement}.`;
  if (newlyAbnormal) {
    note += ` It was inside the reference range before and is now outside it.`;
  } else if (returnedToRange) {
    note += ` It is now back inside the reference range.`;
  } else if (isAbnormal) {
    note += ` It remains outside the reference range.`;
  }

  return { direction, delta, deltaPercent, note, newlyAbnormal, returnedToRange };
}

export interface RecordComparison {
  key: string;
  testName: string;
  unit: string;
  panel: string;
  referenceRange: string;
  earlier: { value: number; status: string } | null;
  later: { value: number; status: string } | null;
  delta: number | null;
  deltaPercent: number | null;
  direction: TrendDirection | 'ADDED' | 'REMOVED';
  newlyAbnormal: boolean;
  returnedToRange: boolean;
}

/**
 * Side-by-side comparison of the parameters in two reports. Parameters present
 * in only one report are reported as ADDED / REMOVED rather than silently
 * dropped — a test that stopped being ordered is itself information.
 */
export function compareParameters(
  earlierParams: ExtractedParameter[],
  laterParams: ExtractedParameter[]
): RecordComparison[] {
  const earlierByKey = new Map(earlierParams.map((p) => [p.key, p]));
  const laterByKey = new Map(laterParams.map((p) => [p.key, p]));
  const keys = new Set([...earlierByKey.keys(), ...laterByKey.keys()]);

  const rows: RecordComparison[] = [];
  for (const key of keys) {
    const a = earlierByKey.get(key);
    const b = laterByKey.get(key);
    const reference = b ?? a!;

    if (!a || !b) {
      rows.push({
        key,
        testName: reference.testName,
        unit: reference.unit,
        panel: reference.panel,
        referenceRange: reference.referenceRange,
        earlier: a ? { value: a.value, status: a.status } : null,
        later: b ? { value: b.value, status: b.status } : null,
        delta: null,
        deltaPercent: null,
        direction: b ? 'ADDED' : 'REMOVED',
        newlyAbnormal: false,
        returnedToRange: false,
      });
      continue;
    }

    const delta = b.value - a.value;
    const relative = a.value !== 0 ? Math.abs(delta / a.value) : Math.abs(delta);
    const wasAbnormal = a.status === 'HIGH' || a.status === 'LOW';
    const isAbnormal = b.status === 'HIGH' || b.status === 'LOW';

    rows.push({
      key,
      testName: b.testName,
      unit: b.unit,
      panel: b.panel,
      referenceRange: b.referenceRange,
      earlier: { value: a.value, status: a.status },
      later: { value: b.value, status: b.status },
      delta,
      deltaPercent: a.value !== 0 ? (delta / Math.abs(a.value)) * 100 : null,
      direction: relative < STABLE_THRESHOLD ? 'STABLE' : delta > 0 ? 'INCREASED' : 'DECREASED',
      newlyAbnormal: !wasAbnormal && isAbnormal,
      returnedToRange: wasAbnormal && b.status === 'NORMAL',
    });
  }

  return rows.sort((x, y) => x.panel.localeCompare(y.panel) || x.testName.localeCompare(y.testName));
}
