"""Generate SYNTHETIC medical reports for development and demonstration.

No real patient information is used anywhere in this file. Every name, ID and
value is invented. The generated files are what the demo uploads.

Outputs (written to healthcare-ai/sample-data/):
  1. sample-blood-report-abnormal.pdf  - digital PDF with a real text layer.
     Works with NO Tesseract installed, so it is the safe demo path.
  2. sample-blood-report-normal.pdf    - all values within range.
  3. sample-lipid-profile-scan.png     - a rasterised page that genuinely
     exercises the Tesseract OCR path.
  4. sample-blood-report-scanned.pdf   - image-only PDF (no text layer), which
     forces the OCR branch for PDFs.

Usage:  python scripts/generate_samples.py
"""
from __future__ import annotations

import sys
from pathlib import Path

import fitz  # PyMuPDF

OUT_DIR = Path(__file__).resolve().parent.parent.parent / "sample-data"

HEADER_FONT = "hebo"   # Helvetica-Bold
BODY_FONT = "cour"     # Courier - keeps the value columns aligned
BODY_BOLD = "cobo"     # Courier-Bold


def _report_lines(*, patient: str, patient_id: str, age: str, sex: str,
                  collected: str, reported: str, rows: list) -> list[tuple[str, str]]:
    """Return (style, text) pairs. style in {title, sub, rule, head, row, section}."""
    lines: list[tuple[str, str]] = [
        ("title", "CITYCARE DIAGNOSTIC LABORATORY"),
        ("sub", "Plot 14, Sector 22, Navi Mumbai 400703  |  NABL Ref: SYNTHETIC-DEMO"),
        ("sub", "*** SYNTHETIC SAMPLE REPORT - GENERATED FOR SOFTWARE TESTING ONLY ***"),
        ("rule", ""),
        ("row", f"Patient Name : {patient:<28}Patient ID   : {patient_id}"),
        ("row", f"Age          : {age:<28}Sex          : {sex}"),
        ("row", f"Collected On : {collected:<28}Reported On  : {reported}"),
        ("row", f"Referred By  : {'Dr. A. Menon (synthetic)':<28}Sample Type  : Whole Blood / Serum"),
        ("rule", ""),
        ("head", f"{'TEST':<34}{'RESULT':>10}  {'UNIT':<14}{'REFERENCE INTERVAL':<24}"),
        ("rule", ""),
    ]
    for row in rows:
        if isinstance(row, str):
            lines.append(("section", row))
        else:
            name, value, unit, ref = row
            lines.append(("row", f"{name:<34}{value:>10}  {unit:<14}{ref:<24}"))
    lines += [
        ("rule", ""),
        ("sub", "End of report. Values are fictitious and generated by a script."),
        ("sub", "Not for clinical use. For OneHealth AI demonstration purposes only."),
    ]
    return lines


def render_pdf(path: Path, lines: list[tuple[str, str]]) -> None:
    document = fitz.open()
    page = document.new_page(width=595, height=842)  # A4
    y = 56.0

    for style, text in lines:
        if style == "title":
            page.insert_text((50, y), text, fontname=HEADER_FONT, fontsize=15)
            y += 20
        elif style == "sub":
            page.insert_text((50, y), text, fontname="helv", fontsize=8)
            y += 13
        elif style == "rule":
            y += 4
            page.draw_line(fitz.Point(50, y), fitz.Point(545, y), width=0.7)
            y += 14
        elif style == "head":
            page.insert_text((50, y), text, fontname=BODY_BOLD, fontsize=8.5)
            y += 14
        elif style == "section":
            y += 4
            page.insert_text((50, y), text, fontname=BODY_BOLD, fontsize=8.5)
            y += 14
        else:
            page.insert_text((50, y), text, fontname=BODY_FONT, fontsize=8.5)
            y += 12.5

    document.save(path)
    document.close()


def render_png(path: Path, lines: list[tuple[str, str]], dpi: int = 200) -> None:
    """Rasterise the same report so the OCR path can be demonstrated."""
    tmp = path.with_suffix(".tmp.pdf")
    render_pdf(tmp, lines)
    document = fitz.open(tmp)
    zoom = dpi / 72.0
    pixmap = document[0].get_pixmap(matrix=fitz.Matrix(zoom, zoom))
    pixmap.save(path)
    document.close()
    tmp.unlink()


def render_scanned_pdf(path: Path, lines: list[tuple[str, str]], dpi: int = 180) -> None:
    """An image-only PDF: no text layer at all, so OCR is mandatory."""
    from PIL import Image

    png = path.with_suffix(".tmp.png")
    jpg = path.with_suffix(".tmp.jpg")
    render_png(png, lines, dpi=dpi)
    # JPEG-compress the page so the sample file stays small enough to email/commit.
    Image.open(png).convert("L").save(jpg, "JPEG", quality=80, optimize=True)
    document = fitz.open()
    page = document.new_page(width=595, height=842)
    page.insert_image(fitz.Rect(0, 0, 595, 842), filename=str(jpg))
    document.save(path, deflate=True)
    document.close()
    png.unlink()
    jpg.unlink()


ABNORMAL_ROWS = [
    "--- COMPLETE BLOOD COUNT ---",
    ("Hemoglobin",             "10.4",     "g/dL",         "12.0 - 15.0"),
    ("Total Leukocyte Count",  "12800",    "/cumm",        "4000 - 11000"),
    ("Red Blood Cell Count",   "3.9",      "million/cumm", "4.1 - 5.1"),
    ("Platelet Count",         "2,45,000", "/cumm",        "150000 - 450000"),
    "--- DIABETES PROFILE ---",
    ("Fasting Blood Glucose",  "126",      "mg/dL",        "70 - 99"),
    ("HbA1c",                  "6.8",      "%",            "4.0 - 5.6"),
    "--- LIPID PROFILE ---",
    ("Total Cholesterol",      "248",      "mg/dL",        "< 200"),
    ("LDL Cholesterol",        "168",      "mg/dL",        "< 100"),
    ("HDL Cholesterol",        "38",       "mg/dL",        "> 50"),
    ("Triglycerides",          "210",      "mg/dL",        "< 150"),
    "--- LIVER FUNCTION ---",
    ("SGPT (ALT)",             "64",       "U/L",          "7 - 56"),
    ("SGOT (AST)",             "38",       "U/L",          "10 - 40"),
    "--- KIDNEY AND THYROID ---",
    ("Serum Creatinine",       "0.9",      "mg/dL",        "0.6 - 1.1"),
    ("TSH",                    "3.2",      "mIU/L",        "0.4 - 4.0"),
]

NORMAL_ROWS = [
    "--- COMPLETE BLOOD COUNT ---",
    ("Hemoglobin",             "14.6",     "g/dL",         "13.0 - 17.0"),
    ("Total Leukocyte Count",  "7200",     "/cumm",        "4000 - 11000"),
    ("Red Blood Cell Count",   "5.1",      "million/cumm", "4.5 - 5.9"),
    ("Platelet Count",         "2,60,000", "/cumm",        "150000 - 450000"),
    "--- DIABETES PROFILE ---",
    ("Fasting Blood Glucose",  "88",       "mg/dL",        "70 - 99"),
    ("HbA1c",                  "5.2",      "%",            "4.0 - 5.6"),
    "--- LIPID PROFILE ---",
    ("Total Cholesterol",      "172",      "mg/dL",        "< 200"),
    ("LDL Cholesterol",        "92",       "mg/dL",        "< 100"),
    ("HDL Cholesterol",        "54",       "mg/dL",        "> 40"),
    ("Triglycerides",          "118",      "mg/dL",        "< 150"),
    "--- LIVER FUNCTION ---",
    ("SGPT (ALT)",             "28",       "U/L",          "7 - 56"),
    ("SGOT (AST)",             "24",       "U/L",          "10 - 40"),
    "--- KIDNEY AND THYROID ---",
    ("Serum Creatinine",       "1.0",      "mg/dL",        "0.7 - 1.3"),
    ("TSH",                    "2.1",      "mIU/L",        "0.4 - 4.0"),
]

LIPID_ROWS = [
    "--- LIPID PROFILE (FASTING) ---",
    ("Total Cholesterol",      "232",      "mg/dL",        "< 200"),
    ("LDL Cholesterol",        "154",      "mg/dL",        "< 100"),
    ("HDL Cholesterol",        "36",       "mg/dL",        "> 40"),
    ("Triglycerides",          "196",      "mg/dL",        "< 150"),
    "--- LIVER FUNCTION ---",
    ("SGPT (ALT)",             "48",       "U/L",          "7 - 56"),
    ("SGOT (AST)",             "31",       "U/L",          "10 - 40"),
]


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    abnormal = _report_lines(
        patient="Ananya Sharma (synthetic)", patient_id="OHA-DEMO-1042",
        age="34 Years", sex="Female",
        collected="12-Aug-2026 08:15", reported="13-Aug-2026 11:40",
        rows=ABNORMAL_ROWS,
    )
    normal = _report_lines(
        patient="Rohan Verma (synthetic)", patient_id="OHA-DEMO-1043",
        age="29 Years", sex="Male",
        collected="02-Sep-2026 07:50", reported="02-Sep-2026 16:05",
        rows=NORMAL_ROWS,
    )
    lipid = _report_lines(
        patient="Ananya Sharma (synthetic)", patient_id="OHA-DEMO-1042",
        age="34 Years", sex="Female",
        collected="20-Aug-2026 08:05", reported="20-Aug-2026 15:20",
        rows=LIPID_ROWS,
    )

    render_pdf(OUT_DIR / "sample-blood-report-abnormal.pdf", abnormal)
    render_pdf(OUT_DIR / "sample-blood-report-normal.pdf", normal)
    render_png(OUT_DIR / "sample-lipid-profile-scan.png", lipid)
    render_scanned_pdf(OUT_DIR / "sample-blood-report-scanned.pdf", abnormal)

    print(f"Synthetic sample reports written to: {OUT_DIR}")
    for item in sorted(OUT_DIR.iterdir()):
        print(f"  {item.name:<42}{item.stat().st_size:>9,} bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main())
